[package]
name = "rori"
version = "0.3.0"
edition = "2024"
readme = "README.md"
description = "A highly multithreaded tool for deleting inactive chunks or regions in Minecraft worlds, focusing on performance and efficiency, designed to be used for large-scale world management."
repository = "https://github.com/qtchaos/rori"
license = "GNU General Public License v3.0 or later"
keywords = ["minecraft", "nbt",]
authors = ["chaos"]

[dev-dependencies]
criterion = { package = "codspeed-criterion-compat", version = "3.0.5", default-features = false }
proptest = { version = "1.5", features = ["std"], default-features = false }

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
env_logger = { version = "0.11.8", default-features = false }
fastanvil = { version = "0.31.0", default-features = false }
libdeflater = "1.22"
indicatif = { version = "0.18.0", default-features = false }
log = "0.4.27"
num_cpus = "1.17.0"
rayon = "1.10.0"
memmap2 = "0.6.2"

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false

[profile.release]
lto = "fat"
strip = "debuginfo"
codegen-units = 1
opt-level = 3
panic = "abort"

[profile.bench]
debug = true
strip = "none"
lto = "fat"
codegen-units = 1

[[bench]]
name = "process_directory"
harness = false

[[bench]]
name = "nbt_reader"
harness = false

[[bench]]
name = "decompress_chunk"
harness = false

[[bin]]
name = "rori"
path = "src/main.rs"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
inline_always = "allow"
missing_errors_doc = "allow"
literal_string_with_formatting_args = "allow"
